### ISSUE TITLE
XEPs support file and verification of the version support

### ISSUE THREAD

**Issue by Neustradamus** [sstrigler/JSJaC#62]
It will be nice to create a file with all XEPs support (with the version number) and verify if it is the last version, if not, it is the time to update ;)

Link: http://xmpp.org/xmpp-protocols/xmpp-extensions/

**Comment by Neustradamus** [comment]
It is possible to know what XEPs are really supported by JSJaC and what version?
It works with last RFCs?

**Comment by sstrigler** [comment]
JsJaC implements RFC6120 (XMPP Core), Websockets and BOSH but no more. It is a low level client library. It allows you to implement any client side XEP and maybe even beyond but that’s out of scope for this project.

**Comment by Neustradamus** [comment]
@sstrigler: it will be nice to specify in a file the RFCs and XEPs with version :)

**Comment by Neustradamus** [comment]
Example:
- RFCXXXX
- XEP-XXXX v1.2
