### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [sstrigler/JSJaC#70]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/gajimxepsupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by Neustradamus** [comment]
It is possible to know what XEPs are really supported by JSJaC and what version?
It works with last RFCs?

**Comment by sstrigler** [comment]
JsJaC is not a client but a client library. It doesn’t implement any of the XEPs. It’s up to the developer to implement what they need.

**Comment by Neustradamus** [comment]
It will be nice to note what XMPP RFCs :)

**Comment by Neustradamus** [comment]
Example:
- RFCXXXX
- XEP-XXXX v1.2
