### ISSUE TITLE
Websockets Prebound session

### ISSUE THREAD

**Issue by cobrowserAlex** [sstrigler/JSJaC#79]
We are pre-binding sessions on our server and supplying the web client the jid/rid/sid. We then use Connection.inherit() to 'resume' that session. I was wondering if such a pre-bind mechanism can be achieved with the Websocket connection as well? I see there is no 'inherit' method on the websocket connection, but maybe it can be achieved another way?

**Comment by sstrigler** [comment]
You might by using Stream Session Management (XEP 0198), but I haven't tried it.

If you have means to authenticate websocket connections in some other way (before they hit the server) you might just as well just skip the authentication in total. This would require quite some "hack" though regarding your XMPP server.

**Comment by cobrowserAlex** [comment]
Thanks @sstrigler for your super fast reply. Will have a look.

I want to make a point of thanking you and the contributors for this rock solid library!
