### ISSUE TITLE
Possible to not use cookie?

### ISSUE THREAD

**Issue by cobrowserAlex** [sstrigler/JSJaC#82]
We use the library with pre-bound sessions and have no need for a cookie to resume a connection.
Is the cookie necessary for JsJac to function?

The problem is that we have some clients' websites running in infrastructure that doesn't like the cookie:
Getting "a potentially dangerous Request.Cookies values was detected from the client..."
Screenshot:
http://www.screencast.com/t/XdwZaaUQ

If you never need the cookie to resume anything, then would it be feasible to add a parameter to not use a cookie?

**Comment by sstrigler** [comment]
The only occurrence where the cookie is created is when you'd do a <JSJaCConnection>.suspend(). Probably done within your onunload handler. Just remove this.
If you still want to be able to store the current state (so that you can restore from it) there is <JSJaCConnection>.suspendToData().

**Comment by cobrowserAlex** [comment]
Tnx @sstrigler
