### ISSUE TITLE
BOSH over websocket not work.

### ISSUE THREAD

**Issue by sonnguyen1205** [sstrigler/JSJaC#83]
I using websocket plugin on openfire 3.10.2 to using BOSH over websocket but not work, with notice " status changed: connecting ".
I have fixing it.

[websocket.zip](https://github.com/sstrigler/JSJaC/files/395262/websocket.zip)

**Comment by rraptorr** [comment]
If you want to contribute a fix, please create a pull request with your changes. Attaching random zip files is really not how GitHub works ;)

**Comment by sonnguyen1205** [comment]
thanks for help 👍
