### ISSUE TITLE
XMPP Core

### ISSUE THREAD

**Issue by Neustradamus** [sstrigler/JSJaC#89]
For be perfect with the actual XMPP network:
https://xmpp.org/extensions/xep-0387.html
- http://tools.ietf.org/html/rfc6120
- http://tools.ietf.org/html/rfc6121
- https://tools.ietf.org/html/rfc7622
- ...

**Comment by sstrigler** [comment]
Jsjac is neither a server nor a client. It’s a library.

**Comment by Neustradamus** [comment]
Old RFCs are different from new RFCs no for the lib?
